platform:ios, '7.0'
inhibit_all_warnings!
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 2.5.5’
pod 'Masonry', '~> 0.6.2'
pod 'sqlite3', '~> 3.8.11.1'
pod 'IMQuickSearch', '~> 1.2.0'
